# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tambah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=25)),
                ('tanggallahir', models.DateTimeField(default='')),
                ('jeniskelamin', models.CharField(max_length=10)),
                ('rt', models.CharField(max_length=3)),
                ('alamat', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
