# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_tambahpengumuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tambahpengumuman',
            name='kategori',
            field=models.CharField(max_length=255),
        ),
    ]
