# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_auto_20190622_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='tambahpengumuman',
            name='pembuat',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
