# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_tambahpengumuman_pembuat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tambahpengumuman',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='tambahpengumuman',
            name='pembuat',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
