# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_auto_20190623_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='dokumentasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('gambarutama', models.ImageField(blank=True, null=True, upload_to='')),
                ('gambar1', models.ImageField(blank=True, null=True, upload_to='')),
                ('gambar2', models.ImageField(blank=True, null=True, upload_to='')),
                ('gambar3', models.ImageField(blank=True, null=True, upload_to='')),
                ('gambar4', models.ImageField(blank=True, null=True, upload_to='')),
                ('gambar5', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
